### ISSUE TITLE
Control won't load First Name/Last Name data

### ISSUE THREAD

**Issue by iozm** [AndrewButenko/FullNameControl#5]
Hello, just installed FullNameControl in my DEV environment, and I noticed that the First and Last Name fields don't display the data on existing records the first time I open them. But if I refresh the record the Control will now display the data. This only happens the first time I open an existing record.

**Comment by AndrewButenko** [comment]
Hello,
Do you have fields of firstname and lastname placed on the form?
Andrew

**Comment by iozm** [comment]
Hi Andrew, 

No, the original fields have been removed from the form. Do they need to be present but hidden?

**Comment by AndrewButenko** [comment]
Yes, place it on the form but leave it hidden and everything should work from the first shot.

**Comment by iozm** [comment]
Hi Andrew,

I've verified the behavior with your proposed solution. Control is behaving as expected now. Thanks!
